import 'package:flutter/material.dart';
import 'package:ludo/widget/circle_container.dart';



import 'package:ludo/widget/custome_conatiner.dart';

class blueyellowcontainer extends StatelessWidget {
  const blueyellowcontainer({super.key});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: Row(
        children: [
          Column(
            children: [
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blueGrey),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blueGrey),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blueGrey),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 194, 186, 186)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
            ],
          ),
          Column(
            children: [customcontainer(480, 2, Colors.grey)],
          ),
          Column(
            children: [
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
            ],
          ),
          Column(
            children: [customcontainer(480, 2, Colors.grey)],
          ),
          Column(
            children: [
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
            ],
          ),
          Column(
            children: [customcontainer(480, 2, Colors.grey)],
          ),
          Column(
            children: [
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              circlecontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              circlecontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              circlecontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              circlecontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
            ],
          ),
          Column(
            children: [customcontainer(480, 2, Colors.grey)],
          ),
          Column(
            children: [
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              circlecontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              circlecontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 194, 186, 186)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              circlecontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              circlecontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
            ],
          ),
          Column(
            children: [customcontainer(480, 2, Colors.grey)],
          ),
          Column(
            children: [
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, const Color.fromARGB(255, 125, 189, 241)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Color.fromARGB(255, 245, 234, 141)),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
            ],
          ),
          Column(
            children: [customcontainer(480, 2, Colors.grey)],
          ),
          Column(
            children: [
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.blue),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.white),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
              customcontainer(30, 30, Colors.yellow),
              customcontainer(2, 30, Colors.grey),
            ],
          ),
          Column(
            children: [customcontainer(480, 2, Colors.grey)],
          ),
        ],
      ),
    );
  }
}
